<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="yawlnet" nsURI="http://mbse.gruppexx/yawlnet" nsPrefix="yawl">
  <eClassifiers xsi:type="ecore:EClass" name="Yawlnet" eSuperTypes="../../org.pnml.tools.epnk/model/PNMLCoreModel.ecore#//PetriNetType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="../../org.pnml.tools.epnk/model/PNMLCoreModel.ecore#//Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="join" eType="#//TransitionType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="split" eType="#//TransitionType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arc" eSuperTypes="../../org.pnml.tools.epnk/model/PNMLCoreModel.ecore#//Arc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arctype" eType="#//ArcType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionType" eSuperTypes="../../org.pnml.tools.epnk/model/PNMLCoreModel.ecore#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="#//EnumTransitonTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="../../org.pnml.tools.epnk/model/PNMLCoreModel.ecore#//Place">
    <eStructuralFeatures xsi:type="ecore:EReference" name="placetype" eType="#//PlaceType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArcType" eSuperTypes="../../org.pnml.tools.epnk/model/PNMLCoreModel.ecore#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="#//EnumArcTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlaceType" eSuperTypes="../../org.pnml.tools.epnk/model/PNMLCoreModel.ecore#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="#//EnumPlaceTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumTransitonTypes">
    <eLiterals name="AND" literal="AND"/>
    <eLiterals name="OR" value="1" literal="OR"/>
    <eLiterals name="XOR" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumArcTypes">
    <eLiterals name="RESET"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumPlaceTypes">
    <eLiterals name="START"/>
    <eLiterals name="END" value="1"/>
  </eClassifiers>
</ecore:EPackage>
